spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test;MODE=MySQL;
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console

app:
  resource:
    support:
      shorts: mp4, mov, avi, wmv
    local:
      dummy: app-resource/test/dummy/
      shorts: app-resource/test/shorts/

ncp:
  s3:
    end-point: test
    region-name: test
    bucket-name: test
    access-key: test
    secret-key: test